#!/bin/bash -eu
rm -rf ./tmp || true
mkdir tmp

desymlink_all() {
	tar -hcf - node_modules | tar -xf - -C tmp

	rm -rf tmp/node_modules/.bin
	mv node_modules/.bin tmp/node_modules/

	rm -rf node_modules
	mv tmp/node_modules node_modules
}

desymlink_specific() {
	if compgen -G "node_modules/$1" >/dev/null; then
		echo "[desymlink-node-modules] desymlinking $1..."
		tar -hcf - node_modules/$1 | tar -xf - -C tmp
		rm -rf node_modules/$1
	else
		echo "[desymlink-node-modules] no module(s) found matching: $1"
	fi

	if compgen -G "tmp/node_modules/*" >/dev/null; then
		mv tmp/node_modules/* node_modules/
	fi
}

if [[ "$#" = "0" ]]; then
	desymlink_all
elif [[ "$#" = "1" ]]; then
	desymlink_specific "$1"
else
	echo "No support for multiple args yet; try using globs"
	exit 1
fi
