#!/bin/bash -eu
rm -rf ./tmp || true
mkdir tmp

tar -hcf - node_modules | tar -xf - -C tmp

rm -rf tmp/node_modules/.bin
mv node_modules/.bin tmp/node_modules/

rm -rf node_modules
mv tmp/node_modules node_modules
